"""adicionando cep a tabela sala

Revision ID: 1ef47b14b293
Revises: 8fcaa439c9a2
Create Date: 2026-05-16 10:01:05.901127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef47b14b293'
down_revision = '8fcaa439c9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=8), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
